"""Add column status

Revision ID: 0f11de865b4e
Revises: e554208da77a
Create Date: 2024-12-30 14:26:44.025627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f11de865b4e'
down_revision: Union[str, None] = 'e554208da77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    document_index_status_enum = postgresql.ENUM('INDEXING', 'SUCCESS', 'FAILED', name='DocumentIndexStatusEnum')
    document_index_status_enum.create(op.get_bind())
    op.add_column('document', sa.Column('status', postgresql.ENUM('INDEXING', 'SUCCESS', 'FAILED', name='DocumentIndexStatusEnum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'status')
    document_index_status_enum = postgresql.ENUM('INDEXING', 'SUCCESS', 'FAILED', name='DocumentIndexStatusEnum')
    document_index_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
